global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'database-comparison'
    replica: '1'

scrape_configs:
  - job_name: 'database-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'database-comparison-test'
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mongodb-batch-write-performance'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          service: 'mongodb-batch-write-performance-test'
    metrics_path: '/metrics'
    scrape_interval: 5s

